__cached_arm-none-eabi-gcc_-v_2>&1_|_grep_-q_"clang_version"_&&_echo_clang_||_echo_gcc := gcc
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-fno-dwarf2-cfi-asm";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := -fno-dwarf2-cfi-asm
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-mno-unaligned-access";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := -mno-unaligned-access
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-mlittle-endian_-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-fno-ipa-sra_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-fno-ipa-sra";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := -fno-ipa-sra
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-mlittle-endian_-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-fno-ipa-sra_-mapcs-32_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-mapcs-32";_else_echo_"-mabi_apcs-gnu";_fi;_rm_-f_"_TMP"_"_TMPO" := -mabi=apcs-gnu
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-mlittle-endian_-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-fno-ipa-sra_-mno-thumb-interwork_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-mno-thumb-interwork";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := -mno-thumb-interwork
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-mlittle-endian_-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-fno-ipa-sra_-marm_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-marm";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := -marm
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-mlittle-endian_-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-fno-ipa-sra_-malignment-traps_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-malignment-traps";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := 
__cached_set_-e;_TMP_".__.tmp";_TMPO_".__.o";_if____arm-none-eabi-gcc_-Werror__-D__KERNEL___-mlittle-endian_-Wall_-Wundef_-Wstrict-prototypes_-Wno-trigraphs_-fno-strict-aliasing_-fno-common_-fshort-wchar_-Werror-implicit-function-declaration_-Wno-format-security_-std_gnu89_-fno-dwarf2-cfi-asm_-mno-unaligned-access_-fno-ipa-sra_-mshort-load-bytes_-c_-x_c_/dev/null_-o_"_TMP"__>/dev/null_2>&1;_then_echo_"-mshort-load-bytes";_else_echo_"";_fi;_rm_-f_"_TMP"_"_TMPO" := 
